  - name: get the username running the deploy
    command: whoami
    become: no
    register: username_on_the_host

  - name: Creates ansible cache directory
    file: path=/home/{{username_on_the_host.stdout}}/{{download_cache}} state=directory recurse=yes
    become: no
