- name: Include Vars
  include_vars: "{{ item }}"
  with_first_found:
    - "variables.yml"

- name: get the username running the deploy
  command: whoami
  become: no
  register: username_on_the_host

- name: Check if android studio is installed
  command: grep {{android_studio_build_text}} {{install_dir}}/build.txt
  register: install
  failed_when: false
  changed_when: false

- name: Get sha256 zip
  stat:
    path: "/home/{{username_on_the_host.stdout}}/{{local_package_location}}"
    checksum_algorithm: sha256
    get_checksum: yes
  register: zip_stat
  become: no

- debug:
    msg: "{{zip_stat}}"

- name: Download Android Studio .zip
  when: (not zip_stat.stat.exists) or (zip_stat.stat.checksum != "{{studio_checksum}}")
  get_url:
    url: "{{linux_url}}"
    dest: "/home/{{username_on_the_host.stdout}}/{{local_package_location}}"
    validate_certs: no
    checksum: sha256:{{studio_checksum}}
  register: download
  become: no

- name: unlink install dir
  file:
    path: "{{install_dir}}"
    state: absent
  when: install.stdout.find(android_studio_build_text) == -1
  become: yes

- name: for debug
  debug:
    msg: "unlink install dir"
  when: install.stdout.find(android_studio_build_text) == -1

- name: Uncompress Android Studio
  unarchive:
    src: "/home/{{username_on_the_host.stdout}}/{{local_package_location}}"
    dest: /opt
  become: yes
  when: install.stdout.find(android_studio_build_text) == -1
