
- name: Install Pyenv
  hosts: localhost
  become: true
  vars_files:
    - vars/variables.yml

  roles:
    - role: pyenv_install
      pyenv_versions:
        - 3.6.5

  tags:
    - toolkit-install
