---
- include: pyenv.yml

- name: get the username running the deploy
  command: whoami
  become: no
  register: username_on_the_host

- name: Check if the disk is partitioned and also ignore sda
  stat: path=/home/{{username_on_the_host.stdout}}/.pyenv/versions/{{item}}
  with_items: "{{pyenv_versions}}"
  register: version_stat

- name: Install versions
  become: no
  command: creates={{pyenv_root}}/versions/{{ item.item }} pyenv install {{ item.item }}
  with_items: "{{version_stat.results}}"
  when:
    - item.stat.exists == false

- name: Add pyenv environment variables to profile
  template: src=pyenv-init.j2 dest=/etc/profile.d/pyenv-init.sh
  become: yes
  tags: [pyenv]
