# Install emacs from source using ansible
#
# Usage: ansible-playbook emacs.yml


# The MIT License (MIT)
#
# Copyright (c) 2015 George M Jones
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

---
# Pull emacs sources, but no more often than once a week

- name: get the username running the deploy
  command: whoami
  become: no
  register: username_on_the_host

- name: Include Vars
  include_vars: "{{ item }}"
  with_first_found:
    - "variables.yml"

- include: dependencies.yml

- stat: path=~/src/emacs/
  register: pulled
  become: no
  tags:
    - pull

- name: use file module to create a timestamp file for "now"
  file: path="~/ansible.now" state=touch
  tags:
    - pull

- stat: path=~/ansible.now
  register: now
  tags:
    - pull

- name: Setup | pull latest emacs sources
  when: ((not pulled.stat.exists) or
         (pulled.stat.exists and pulled.stat.mtime  + secondsPerWeek < now.stat.mtime))
  git: repo=git://git.savannah.gnu.org/emacs.git accept_hostkey=true dest=~/src/emacs
  register: src
  become: no
  tags:
    - pull

# build from source just pulled.  These take a while
- name: Setup | autogen
  when: src.changed
  command: ./autogen.sh chdir=~/src/emacs
  register: autogen
  become: no
  tags:
    - build

- debug:
    msg: "{{autogen}}"
#
- name: Setup | configure
  when: autogen.changed
  command: ./configure --enable-link-time-optimization --without-pop --without-kerberos --without-kerberos5 --without-hesiod --with-sound=alsa --with-x-toolkit=gtk3 --with-xpm --with-jpeg --with-tiff --with-gif --with-png --with-rsvg  --with-xml2 --with-imagemagick --with-xft --without-libotf --without-xim --with-xaw3d --with-dbus --without-gconf --without-gsettings --without-selinux --with-gnutls --with-zlib --with-modules --with-file-notification=inotify --without-makeinfo --with-x --exec-prefix=/usr/ chdir=~/src/emacs
  register: configure
  become: no
  tags:
    - build

- name: Setup | bootstrap
  when: configure.changed
  command: make bootstrap -j8 chdir=~/src/emacs
  register: bootstrap
  become: no
  tags:
    - build

- debug:
    msg: "{{bootstrap}}"
# install
- name: Setup | install
  when: bootstrap.changed
  command: make install chdir=/home/{{username_on_the_host.stdout}}/src/emacs
  become: yes
  tags:
    - install

- name: Add emacs environment variables to profile
  template: src=emacs-init.j2 dest=/etc/profile.d/emacs-init.sh
  become: yes
  tags:
    - setup

- name: Setup | remember when we last pulled emacs sources
  file: path=~/src/emacs/  state=touch
  become: no
  tags:
      - pull

- include: config.yml
