- name: get the username running the deploy
  command: whoami
  become: no
  register: username_on_the_host

- stat: path="{{sync_work.dest_dir}}"
  register: pulled
  become: no
  tags:
    - pull

- name: use file module to create a timestamp file for "now"
  file: path="~/ansible.now" state=touch
  tags:
    - pull

- stat: path=~/ansible.now
  register: now
  tags:
    - pull


- name: Pull latest {{sync_work.repo_url}} sources
  when: ((not pulled.stat.exists) or
         (pulled.stat.exists and pulled.stat.mtime  + secondsPerWeek < now.stat.mtime))
  git: repo={{sync_work.repo_url}} accept_hostkey=true dest={{sync_work.dest_dir}} track_submodules=yes force=yes
  register: src
  become: no
  tags:
    - pull

- debug:
    msg: "{{sync_work}} and {{src}}"

- name: Build {{sync_work.dest_dir}} sources
  loop_control:
    loop_var: cmd
  command: "{{cmd}} chdir={{sync_work.dest_dir}}"
  when: src.changed and {{'build_cmd' in sync_work.keys()}}
  with_items: "{{sync_work.build_cmd}}"
  register: configure_make
  become: no
  tags:
    - build

- debug:
    msg: "{{configure_make.changed}}"

- name: Install {{sync_work}} sources
  command: make install chdir={{pulled.stat.path}}
  when: configure_make.changed and {{'install_cmd' in sync_work.keys()}}
  become: yes
  tags:
    - install

- name: Remember when we last pulled {{sync_work.dest_dir}} sources
  file: path={{sync_work.dest_dir}}  state=touch
  become: no
  tags:
      - pull
